#!/bin/bash
# create all user
#


./asset/create-user redis 4201 redis 4201
./asset/create-user elasticsearch 4202 elasticsearch 4202
./asset/create-user mongodb 4203 mongodb 4203
./asset/create-user rabbitmq 4204 rabbitmq 4204
./asset/create-user java 4205 java 4205
./asset/create-user py 4206 py 4206
./asset/create-user node 4207 node 4207
./asset/create-user docker 4242 docker 4242
