#!/bin/bash
# standard uid/gid
USER_NAME=$1
STD_UID=$2
STD_GID=$3


# replace uid/gid of specified user by standardized users

USERLINE=$(cat /etc/passwd | grep $USER_NAME)
ORIG_UID=$(echo $USERLINE | cut -f3 -d:)
ORIG_GID=$(echo $USERLINE | cut -f4 -d:)
ORIG_HOME=$(echo $USERLINE | cut -f6 -d:)
sed -i -e "s/:$ORIG_UID:$ORIG_GID:/:$STD_UID:$STD_GID:/" /etc/passwd
sed -i -e "s/$USER_NAME:x:$ORIG_GID:/$USER_NAME:x:$STD_GID:/" /etc/group

echo "$USER_NAME have now $STD_UID:$STD_GID"
